name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Get EC2 Public IP
      run: |
        EC2_PUBLIC_IP=$(aws ec2 describe-instances \
          --filters "Name=instance-state-name,Values=running" \
          --query "Reservations[*].Instances[*].PublicIpAddress" \
          --output text)
        echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
        echo "Public IP: $EC2_PUBLIC_IP"

    - name: Create known_hosts file
      run: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts

    - name: Add SSH host to known_hosts
      run: ssh-keyscan -H $EC2_PUBLIC_IP >> ~/.ssh/known_hosts

    - name: Add SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy Application
      run: |
        ssh -i key.pem ec2-user@$EC2_PUBLIC_IP "cd /home/ec2-user/my-app && git pull && npm install && npm start"

