name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Keys
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ayan.pem
          chmod 600 ayan.pem
          ssh-keygen -y -f ayan.pem > ayan.pub
          echo "Public key starts with:"
          head -n 1 ayan.pub

      - name: Verify Key Pair
        run: |
          echo "=== Key Verification ==="
          echo "Private key header: $(head -n 1 ayan.pem)"
          echo "Public key type: $(ssh-keygen -y -f ayan.pem | head -n 1 | cut -d' ' -f1)"
          echo "Fingerprint: $(ssh-keygen -lf ayan.pem)"

      - name: Deploy Application
        run: |
          ssh -i ayan.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /home/ubuntu/my-app
          git pull
          npm install
          pm2 restart all
          EOF

      - name: Cleanup
        if: always()
        run: rm -f ayan.pem ayan.pub
