name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ayan.pem
          chmod 400 ayan.pem

      - name: Verify Key
        run: |
          echo "Key verification:"
          head -n 1 ayan.pem
          ssh-keygen -l -f ayan.pem

      - name: Add to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Test Connection
        run: |
          ssh -i ayan.pem -o ConnectTimeout=10 ubuntu@${{ secrets.EC2_PUBLIC_IP }} "echo 'SSH success! Current user: $(whoami)'"

      - name: Deploy Application
        run: |
          ssh -i ayan.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} \
            "cd /home/ubuntu/my-app && \
            git pull && \
            npm install && \
            pm2 restart all"

      - name: Cleanup
        if: always()
        run: rm -f ayan.pem
